In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math

In [26]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[[],1] = 0
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
A = np.random.binomial(1, [[0.1, 0.1],[0.8,0.3]])
print(A.dtype)

int64


In [30]:
def _ComputeExpectedEdgeCounts(num_edges, num_vertices,
                               pi,
                               prop_mat):
  """Computes expected edge counts within and between communities.
  Args:
    num_edges: expected number of edges in the graph.
    num_vertices: number of nodes in the graph
    pi: interable of non-zero community size proportions. Must sum to 1.0, but
      this check is left to the caller of this internal function.
    prop_mat: square, symmetric matrix of community edge count rates. Entries
      must be non-negative, but this check is left to the caller.
  Returns:
    symmetric matrix with shape prop_mat.shape giving expected edge counts.
  """
  print(np.matmul(prop_mat, pi).shape)
  scale = np.matmul(pi, np.matmul(prop_mat, pi)) 
  print(scale)
  prob_mat = prop_mat * num_edges / scale
  return np.outer(pi, pi) * prob_mat

In [31]:
num_edges = 100
num_vertices = 50
pi = np.array([0.7, 0.2, 0.1])
prop_mat = np.array([[5, 1, 1],[1, 5, 1], [1, 1, 5]])

In [32]:
w = _ComputeExpectedEdgeCounts(num_edges, num_vertices, pi, prop_mat)

(3,)
3.16


In [29]:
w / 3.16

array([[77.53164557,  4.43037975,  2.21518987],
       [ 4.43037975,  6.32911392,  0.63291139],
       [ 2.21518987,  0.63291139,  1.58227848]])

In [21]:
np.sum(w, axis=1)

array([84.17721519, 11.39240506,  4.43037975])